version: 2
updates:
  - package-ecosystem: "cargo"
    directory: 
      - "/"
    schedule:
      interval: "weekly"
    groups:
      rhai:
        patterns: ["rhai*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
