# Example development server
# Do not use this in production


# Use postgres/example user/password credentials
# This is a test docker instance, PLEASE DONT USE THIS IN PRODUCTION OR YOU WILL GET PWNED
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  s3:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address=:9001