[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap_mangen = "0.2.9"
anda = { path = ".." }
clap = { version = "4.4.0", features = ["derive", "env"] }
anyhow = "1.0.69"
clap_complete = "4.1.5"