[package]
name = "andax"
version = "0.1.11"
edition = "2021"
license = "MIT"
description = "Andaman scripting runtime"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "~1"
regex = "~1"
lazy_static = "~1"
rhai = { version = "1.17.1", features = ["serde", "internals"] }
ureq = { version = "~2", features = ["json"] }
tracing = "0.1.37"
color-eyre = "0.6.2"
smartstring = "1.0.1"
tempfile = "3.10.1"
anda-config = { version = "0.1.6", path = "../anda-config" }
rhai-fs = "0.1.2"
rhai-url = "0.0.5"
hcl-rs = "0.15.0"
directories = "5.0.1"
chrono = "0.4.31"
