[package]
name = "andax"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
serde_json = "~1"
regex = "~1"
lazy_static = "~1"
rhai = { version = "~1", features = ["serde", "internals"] }
ureq = { version = "~2", features = ["json"] }
log = "~0.4.17"
anda-config = { path = "../anda-config" }
