[package]
name = "andax"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
regex = "1.6.0"
lazy_static = "1.4.0"
rhai = { version = "1.11.0", features = ["serde"] }
ureq = { version = "2.5.0", features = ["json"] }
log = "~0.4.17"
anda-config = { path = "../anda-config" }
