[package]
name = "andax"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "~1"
regex = "~1"
lazy_static = "~1"
rhai = { version = "~1", features = ["serde", "internals"] }
ureq = { version = "~2", features = ["json"] }
anda-config = { path = "../anda-config" }
tracing = "0.1.37"
color-eyre = "0.6.2"
