[package]
name = "anda"
version = "0.1.0"
edition = "2021"
description = "Andaman Package Manager and frontend"
authors = [
    "Cappy Ishihara <cappy@cappuchino.xyz>",
    "windowsboy111 <wboy111@outlook.com>",
]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
crate-type = ["cdylib"]

[dependencies]
clap = { version = "3.2", features = ["derive"] }
pretty_env_logger = "0.4.0"
log = "~0.4.17"
serde = { version = "1.0.137", features = ["derive"] }
serde_derive = "1.0.139"
toml = "0.5.9"
serde_json = "1.0.13"
serde_yaml = "0.8.24"
anyhow = "1.0.58"# Add macro feature so rust-analyzer finally finds the macros
tokio ={ version = "1.20.0", features = ["rt-multi-thread", "macros", "fs", "process"] }
walkdir = "2.3.2"
dotenv = "0.15.0"
uuid = { version = "1.1.2", features = ["serde"] }
chrono = { version = "0.4.2", features = ["serde"] }
reqwest = { version = "0.11.11", features = ["multipart", "json"] }
# tabwriter for pretty printing tables
tabwriter = "1.2.1"
runas = "0.2.1"
mime_guess = "2.0.4"
tar = "0.4.38"
flate2 = "1.0.24"
gitignore = "1.0.7"
proc-macro2 = "1.0.40"

[package.metadata.rpm]
package = "anda"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
anda = { path = "/usr/bin/anda" }
