[package]
name = "anda"
version = "0.1.0"
edition = "2021"
description = "Andaman Package Manager (anda)"
authors = [
    "Cappy Ishihara <cappy@cappuchino.xyz>",
    "windowsboy111 <wboy111@outlook.com>",
]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
crate-type = ["cdylib"]

[dependencies]
clap = "3.2.5"
log4rs = "~1.1.1"
pyo3 = { version = "0.16.5", features = ["auto-initialize"] }
log = "~0.4.17"
serde = "1.0.137"
serde_json = "1.0.13"
serde_yaml = "0.8.24"

[package.metadata.rpm]
package = "anda"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
anda = { path = "/usr/bin/anda" }
