//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::artifacts::Entity as Artifacts;
pub use super::builds::Entity as Builds;
pub use super::composes::Entity as Composes;
pub use super::projects::Entity as Projects;
pub use super::targets::Entity as Targets;
pub use super::users::Entity as Users;
