openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /builds:
    get:
      responses:
        '200':
          description: List of builds, as an array of Build objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Build'
