create sequence projects_id_seq;

create sequence packages_id_seq;

create table if not exists projects
(
    id           integer generated by default as identity
        constraint pkgid
            primary key,
    name         text not null,
    description  text,
    latest_build integer
);

comment on column projects.id is 'Package ID';

comment on column projects.name is 'Name of the package';

comment on column projects.description is 'Description of the package';

comment on column projects.latest_build is 'ID of latest build';

alter sequence projects_id_seq owned by projects.id;

alter sequence packages_id_seq owned by projects.id;

create table if not exists users
(
    id   integer generated by default as identity
        constraint uid
            primary key,
    name text not null
        constraint username
            unique,
    type text not null
);

create table if not exists composes
(
    id     text not null
        constraint composes_pk
            primary key,
    target integer
);

comment on table composes is 'Exported Repositories';

create unique index if not exists composes_id_uindex
    on composes (id);

create table if not exists targets
(
    id             integer not null
        constraint targetid
            primary key,
    name           text,
    external_repos text[]
);

create table if not exists builds
(
    id         integer generated by default as identity
        constraint builds_pk_2
            primary key,
    name       text                                   not null,
    package_id integer
        constraint builds_packages_id_fk
            references projects,
    owner      integer
        constraint builds_owner
            references users,
    build_type text                                   not null,
    version    text                                   not null,
    timestamp  timestamp with time zone default now() not null,
    for_target integer
        constraint builds_targets_id_fk
            references targets,
    status     text,
    worker     integer
);

comment on column builds.package_id is 'Package ID, none if test build';

create table if not exists artifacts
(
    id         text not null
        constraint artifacts_pk
            primary key,
    from_build integer
        constraint artifacts_builds_id_fk
            references builds,
    name       text,
    art_type   text,
    timestamp  timestamp with time zone default now()
);

