[package]
name = "rpmspec-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
pest = { version = "2.4.0", features = ["serde", "pretty-print"] }
pest_derive = "2.4.0"
serde = { version = "1.0.145", features = ["derive"] }
regex = "1.6.0"
anyhow = "1.0.59"
lazy_static = "1.4.0"
file-matcher = "0.7.0"
glob = "0.3.0"
