max_width = 200
use_small_heuristics = "Max"
edition = "2021"
merge_derives = true
match_block_trailing_comma = false
use_field_init_shorthand = true
use_try_shorthand = true
hard_tabs = true
fn_args_layout = "compressed"
