[package]
name = "anda-uris"
version = "0.1.0"
edition = "2021"
description = "URI types for Andaman"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "~2"
