name: Package Git build
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  anda:
    strategy:
      matrix:
        version: ["f44"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - uses: actions/checkout@v6
      - uses: FyraLabs/anda-build@6ec778c6024582cfd3c78c77e398a99996481e58
        with:
          name: "anda-git"
          mockConfig: terra-44-${{ matrix.arch }}
