name: Package Git build
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  anda:
    strategy:
      matrix:
        version: ["f43"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: FyraLabs/anda-build@main
        with:
          name: "anda-git"
          mockConfig: terra-44-${{ matrix.arch }}
