name: Package Release

on:
  push:
    paths:
      - rust-anda.spec
    branches: [main]
  workflow_dispatch:

jobs:
  anda:
    strategy:
      matrix:
        version: ["ad37"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - uses: actions/checkout@v2
      - uses: terrapkg/anda-build@main
        with:
          name: "anda"
          mockConfig: anda-37-${{ matrix.arch }}
          andaRepo: https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra37.repo


      - name: Upload packages to subatomic
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            ${{ matrix.version }} anda-build/rpm/rpms/*
