name: Package

on:
  push:
    paths:
      - rust-anda.spec
      - anda.hcl
    branches: [main]
  workflow_dispatch:

jobs:
  anda:
    uses: tau-OS/github-actions/.github/workflows/anda-rpm.yml@main
    with:
      name: "anda"
      subatomicServer: "https://subatomic.fyralabs.com"
      subatomicRepo: fe37
      upload: true
    secrets:
      subatomicToken: ${{ secrets.SUBATOMIC_TOKEN }}
