name: Publish Crate
permissions:
  contents: read
on:
  release:
    types: [published]

      
jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # - uses: manoadamro/rust-release@v1
      #   with:
      #     owner: ${{ github.repository_owner }}
      #     repo: ${{ github.repository }}
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@02cc2f1ad653fb25c7d1ff9eb590a8a50d06186b # v2
        name: Publish to crates.io
        with:
            registry-token: ${{ secrets.CRATES_IO_TOKEN }}
