name: Rust
permissions:
  contents: read
on:
  pull_request:
  push:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

  sccache-setup:
    needs: git
    strategy:
      matrix:
        version: ["f44"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Configure sccache
        id: sccache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          SCCACHE_GHA_VERSION: anda-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}
          SCCACHE_GHA_CACHE_FROM: anda-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}
        with:
          script: |
            const script = require('./.github/scripts/configure-sccache.js')
            await script({github, context, core, exec})

  rust:
    permissions:
      security-events: write
      contents: read
    uses: FyraLabs/actions/.github/workflows/rust.yml@main

  sccache:
    needs: sccache-setup
    strategy:
      matrix:
        version: ["f44"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Report Cache Summary
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('./.github/scripts/sccache-stats.js')
            await script({github, context, core, exec})
