name: Rust
permissions:
  contents: read
on:
  push:
  pull_request:

jobs:
  rust:
    permissions:
      security-events: read
      contents: read
      pull-requests: read
    uses: FyraLabs/actions/.github/workflows/rust.yml@main
